### ISSUE TITLE
db:migrate doesn't work

### ISSUE THREAD

**Issue by rhz** [RevolucionDemocraticaChile/demonet#15]
Quise ver como va el sitio pero despues de hacer un git pull me encontre con esto:

    $ bundle exec rake db:migrate
    rake aborted!
    SyntaxError: /home/rhz/src/ruby/demonet-2/config/application.rb:25: no .<digit> floating literal anymore; put 0 before dot
        DEMONET_VERSION = 0.1.0
                          ^
    /home/rhz/src/ruby/demonet-2/config/application.rb:25: syntax error, unexpected tINTEGER, expecting '('
    /home/rhz/src/ruby/demonet-2/Rakefile:4:in `require'
    /home/rhz/src/ruby/demonet-2/Rakefile:4:in `<top (required)>'
    (See full trace by running task with --trace)

Hice un git clone ... & git checkout development, seguido de un bundle install, para asegurarme que no seria algo de mi copia y el problema sigue ahi.

**Comment by jjatria** [comment]
Depende de los errores. :P
En todo caso, me imagino que esto está solucionado? Por el momento, cierro el issue.
