### ISSUE TITLE
Tienes un demo para previsualizar

### ISSUE THREAD

**Issue by johnfelipe** [RevolucionDemocraticaChile/demonet#19]
Tienes un demo para previsualizar
Gracias

**Comment by johnfelipe** [comment]
Hola, tienes un demo

**Comment by jjatria** [comment]
Gracias por el interés, pero no tenemos todavía un demo abierto al público. Cuando haya uno pondremos un link en readme.

**Comment by johnfelipe** [comment]
O unos pantallazos para entender q es demonet?

**Comment by jjatria** [comment]
No, lo siento.

Demonet es una intranet pensada para movimientos políticos, pero quizás aplicable a otras organizaciones también. No hay mucho todavía para mostrar, pero si quieres puedes seguir las instrucciones en el readme e instalar una versión local para ver en qué está.

Salud.

**Comment by johnfelipe** [comment]
Y depronto unos pantallazos de visualizacion de los CRUD o procesos

**Comment by jjatria** [comment]
@johnfelipe, el progreso en demonet está por el momento detenido hasta donde sé. Si te interesa ver de qué se trata, siéntete libre de instalar una versión local y probarla tú mismo. No hay planes inmediatos de abrir demos públicos.

Como dije antes, si la situación cambia será anunciado en el readme, y si estás siguiendo el proyecto serás notificado. Mientras no seas notificado, significará que no ha habido cambios.

**Comment by johnfelipe** [comment]
Y pantallazos?

**Comment by jjatria** [comment]
> [No, lo siento.](https://github.com/RevolucionDemocraticaChile/demonet/issues/19#issuecomment-74929657)
