### ISSUE TITLE
Solicitud ayuda

### ISSUE THREAD

**Issue by rockamu** [RevolucionDemocraticaChile/demonet#22]
Solicitud ayuda este plataforma demonet le sirve para nuestra Fundación A Mover las Manos, entre un militante de la RD.

Espero la respuesta

**Comment by sofiazapatazavala** [comment]
Hola!

La plataforma tiene licencia MIT, por lo que puedes clonarla y trabajar bajo esos términos. Si tienes más dudas o requieres ayuda, te sugiero que escribas a web@revoluciondemocratica.cl para que te den una mano.

Saludos, y mucha suerte en tu proyecto.
